var yzpDrag=angular.module("app",[]);
yzpDrag.directive("yzpDrag",function(){
	return{
		restrict:'A',
		link:function($scope,$elm,$attrs){
			$scope.yzpDrag={};
			$elm.bind("mousedown",function(event){
				$scope.yzpDrag.onDrag=true;
				$scope.yzpDrag.mousedownstartX=event.clientX;
				$scope.yzpDrag.mousedownstartY=event.clientY;
				$scope.yzpDrag.elementstartX=$scope.x;
				$scope.yzpDrag.elementstartY=$scope.y;
			});
			$elm.bind("mousemove",function(event){
				if($scope.yzpDrag.onDrag){
					$scope.$apply(function(){
						$scope.$eval($attrs.yzpDrag);
					})
				}
			});
			$elm.bind("mouseup",function(){
				$scope.yzpDrag.onDrag=false;
			})
		}
	}
});
